name: week10

channels:
  # Conda forge - gives us lots of community-built Python packages, see https://conda-forge.org/ for details
  - conda-forge  
  # R packages - uncoment this one if you want to use R for your work. R packages in conda are generally called 'r-$packagename'. Note that this will massively slow down the dependency resolver so only do it if you actually need it.
  # - r

dependencies:
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - ipykernel
  - gensim
  - spacy
  - pip:
    - pyLDAviz
